version : '3.8'
networks:
  isolation-network:
    driver: bridge
services :
  mongo :
    container_name: mongo
    image : mongo
    restart : always
    ports :
      - "27017:27017"
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: secret
    volumes :
      - mongo-data:/data/db
    networks :
      - isolation-network

  nodejs :
    container_name : nodejs
    build :
      dockerfile : Dockerfile
      context : ./node-app
    depends_on :
      - mongo
    restart : unless-stopped
    volumes :
      - ./node-app:/usr/app
      - /usr/app/node_modules
    env_file : node-app/.env
    ports : ['8181:8181']
    environment :
      - MONGO_URL=mongodb://mongo:27017/mydb
    networks :
      - isolation-network

  vue :
    build :
      dockerfile : Dockerfile
      context : ./vue-app
    volumes :
      - ./vue-app:/app
      - /app/node_modules
    container_name : vue-app
    restart : unless-stopped
    ports :
      - '8080:8080'
    environment:
      - BACKEND_URL=localhost:8181
    networks :
     - isolation-network
    command : /bin/sh -c "npm run serve"


  mongo-express :
    image : mongo-express
    restart : always
    ports :
      - "8081:8081"
  #    environment :
  #            ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #            ME_CONFIG_MONGODB_ADMINPASSWORD: secret
  #            ME_CONFIG_BASICAUTH_USERNAME: admin
  #            ME_CONFIG_BASICAUTH_PASSWORD: secret
    networks :
      - isolation-network
volumes :
  mongo-data :